services:
  taskmanager:
    image: ${DOCKER_REGISTRY-}taskmanager
    build:
      context: .
      dockerfile: TaskManager/Dockerfile
    depends_on:
        - sqldata

  sqldata:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
        - MSSQL_SA_PASSWORD=Opa#2024
        - ACCEPT_EULA=Y
    ports:
        - "1433:1433"